[package]
name = "libhca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
numeric_cast = "0.2"
libudev = "0.3"
scopeguard = "1.2"

[build-dependencies]
bindgen = "0.69"
cc = "1.0"
